/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Sep 10 13:42:57 2019. */

#include "test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t vehicle_state_fields[7] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, vehicle_state, state, state, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, vehicle_state, curHeelAngle, state, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, vehicle_state, maxHeelAngle, curHeelAngle, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, vehicle_state, controlAngle, maxHeelAngle, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, vehicle_state, windAngle, controlAngle, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, vehicle_state, vIn, windAngle, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
