# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessagesServices.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TrimTabMessages_pb2 as TrimTabMessages__pb2
import ArduinoMessages_pb2 as ArduinoMessages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessagesServices.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16MessagesServices.proto\x1a\x15TrimTabMessages.proto\x1a\x15\x41rduinoMessages.proto\"\xbf\x01\n\nAirmarData\x12\x12\n\nwind_speed\x18\x01 \x01(\x02\x12\x10\n\x08wind_dir\x18\x02 \x01(\x02\x12\x10\n\x08\x61ir_temp\x18\x03 \x01(\x02\x12\x0f\n\x07rel_hum\x18\x04 \x01(\x02\x12\x12\n\nbaro_press\x18\x05 \x01(\x02\x1a*\n\x07\x43ompass\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a(\n\tPitchRoll\x12\r\n\x05pitch\x18\x01 \x01(\x02\x12\x0c\n\x04roll\x18\x02 \x01(\x02\"\x13\n\x03req\x12\x0c\n\x04succ\x18\x01 \x01(\x08\"M\n\rControlValues\x12\x13\n\x0brudderAngle\x18\x01 \x01(\x02\x12\x11\n\ttrimAngle\x18\x02 \x01(\x02\x12\x14\n\x0c\x62\x61llastAngle\x18\x03 \x01(\x02\" \n\x08Readings\x12\x14\n\x0c\x61pparentWind\x18\x01 \x01(\x02\"\x1d\n\x0eServer_request\x12\x0b\n\x03req\x18\x01 \x01(\x08\"\x8e\x01\n\x0fServer_response\x12\x1a\n\x12\x61pparent_trim_wind\x18\x01 \x01(\x02\x12\x12\n\ntrim_angle\x18\x02 \x01(\x02\x12\x14\n\x0crudder_angle\x18\x03 \x01(\x02\x12\x15\n\rballast_angle\x18\x04 \x01(\x02\x12\x1e\n\npwm_values\x18\x05 \x01(\x0b\x32\n.PWMValues24\n\x0c\x41irmarReader\x12$\n\rGetAirmarData\x12\x04.req\x1a\x0b.AirmarData\"\x00\x32K\n\x15\x41utonomousValueReader\x12\x32\n\x13GetAutonomousValues\x12\t.Readings\x1a\x0e.ControlValues\"\x00\x32\x39\n\tPWMReader\x12,\n\x0cGetPWMInputs\x12\x0e.ControlAngles\x1a\n.PWMValues\"\x00\x32\x41\n\rTrimTabGetter\x12\x30\n\x11GetTrimTabSetting\x12\r.ApparentWind\x1a\n.TrimAngle\"\x00\x32\x45\n\tWebserver\x12\x38\n\x11MakeServerRequest\x12\x0f.Server_request\x1a\x10.Server_response\"\x00\x62\x06proto3')
  ,
  dependencies=[TrimTabMessages__pb2.DESCRIPTOR,ArduinoMessages__pb2.DESCRIPTOR,])




_AIRMARDATA_COMPASS = _descriptor.Descriptor(
  name='Compass',
  full_name='AirmarData.Compass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='AirmarData.Compass.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AirmarData.Compass.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='AirmarData.Compass.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=222,
)

_AIRMARDATA_PITCHROLL = _descriptor.Descriptor(
  name='PitchRoll',
  full_name='AirmarData.PitchRoll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pitch', full_name='AirmarData.PitchRoll.pitch', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='AirmarData.PitchRoll.roll', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=264,
)

_AIRMARDATA = _descriptor.Descriptor(
  name='AirmarData',
  full_name='AirmarData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='AirmarData.wind_speed', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_dir', full_name='AirmarData.wind_dir', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='air_temp', full_name='AirmarData.air_temp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rel_hum', full_name='AirmarData.rel_hum', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='baro_press', full_name='AirmarData.baro_press', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AIRMARDATA_COMPASS, _AIRMARDATA_PITCHROLL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=264,
)


_REQ = _descriptor.Descriptor(
  name='req',
  full_name='req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='succ', full_name='req.succ', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=285,
)


_CONTROLVALUES = _descriptor.Descriptor(
  name='ControlValues',
  full_name='ControlValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rudderAngle', full_name='ControlValues.rudderAngle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trimAngle', full_name='ControlValues.trimAngle', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ballastAngle', full_name='ControlValues.ballastAngle', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=364,
)


_READINGS = _descriptor.Descriptor(
  name='Readings',
  full_name='Readings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apparentWind', full_name='Readings.apparentWind', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=398,
)


_SERVER_REQUEST = _descriptor.Descriptor(
  name='Server_request',
  full_name='Server_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='Server_request.req', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=429,
)


_SERVER_RESPONSE = _descriptor.Descriptor(
  name='Server_response',
  full_name='Server_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apparent_trim_wind', full_name='Server_response.apparent_trim_wind', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trim_angle', full_name='Server_response.trim_angle', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rudder_angle', full_name='Server_response.rudder_angle', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ballast_angle', full_name='Server_response.ballast_angle', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwm_values', full_name='Server_response.pwm_values', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=574,
)

_AIRMARDATA_COMPASS.containing_type = _AIRMARDATA
_AIRMARDATA_PITCHROLL.containing_type = _AIRMARDATA
_SERVER_RESPONSE.fields_by_name['pwm_values'].message_type = ArduinoMessages__pb2._PWMVALUES
DESCRIPTOR.message_types_by_name['AirmarData'] = _AIRMARDATA
DESCRIPTOR.message_types_by_name['req'] = _REQ
DESCRIPTOR.message_types_by_name['ControlValues'] = _CONTROLVALUES
DESCRIPTOR.message_types_by_name['Readings'] = _READINGS
DESCRIPTOR.message_types_by_name['Server_request'] = _SERVER_REQUEST
DESCRIPTOR.message_types_by_name['Server_response'] = _SERVER_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AirmarData = _reflection.GeneratedProtocolMessageType('AirmarData', (_message.Message,), {

  'Compass' : _reflection.GeneratedProtocolMessageType('Compass', (_message.Message,), {
    'DESCRIPTOR' : _AIRMARDATA_COMPASS,
    '__module__' : 'MessagesServices_pb2'
    # @@protoc_insertion_point(class_scope:AirmarData.Compass)
    })
  ,

  'PitchRoll' : _reflection.GeneratedProtocolMessageType('PitchRoll', (_message.Message,), {
    'DESCRIPTOR' : _AIRMARDATA_PITCHROLL,
    '__module__' : 'MessagesServices_pb2'
    # @@protoc_insertion_point(class_scope:AirmarData.PitchRoll)
    })
  ,
  'DESCRIPTOR' : _AIRMARDATA,
  '__module__' : 'MessagesServices_pb2'
  # @@protoc_insertion_point(class_scope:AirmarData)
  })
_sym_db.RegisterMessage(AirmarData)
_sym_db.RegisterMessage(AirmarData.Compass)
_sym_db.RegisterMessage(AirmarData.PitchRoll)

req = _reflection.GeneratedProtocolMessageType('req', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'MessagesServices_pb2'
  # @@protoc_insertion_point(class_scope:req)
  })
_sym_db.RegisterMessage(req)

ControlValues = _reflection.GeneratedProtocolMessageType('ControlValues', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLVALUES,
  '__module__' : 'MessagesServices_pb2'
  # @@protoc_insertion_point(class_scope:ControlValues)
  })
_sym_db.RegisterMessage(ControlValues)

Readings = _reflection.GeneratedProtocolMessageType('Readings', (_message.Message,), {
  'DESCRIPTOR' : _READINGS,
  '__module__' : 'MessagesServices_pb2'
  # @@protoc_insertion_point(class_scope:Readings)
  })
_sym_db.RegisterMessage(Readings)

Server_request = _reflection.GeneratedProtocolMessageType('Server_request', (_message.Message,), {
  'DESCRIPTOR' : _SERVER_REQUEST,
  '__module__' : 'MessagesServices_pb2'
  # @@protoc_insertion_point(class_scope:Server_request)
  })
_sym_db.RegisterMessage(Server_request)

Server_response = _reflection.GeneratedProtocolMessageType('Server_response', (_message.Message,), {
  'DESCRIPTOR' : _SERVER_RESPONSE,
  '__module__' : 'MessagesServices_pb2'
  # @@protoc_insertion_point(class_scope:Server_response)
  })
_sym_db.RegisterMessage(Server_response)



_AIRMARREADER = _descriptor.ServiceDescriptor(
  name='AirmarReader',
  full_name='AirmarReader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=576,
  serialized_end=628,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAirmarData',
    full_name='AirmarReader.GetAirmarData',
    index=0,
    containing_service=None,
    input_type=_REQ,
    output_type=_AIRMARDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRMARREADER)

DESCRIPTOR.services_by_name['AirmarReader'] = _AIRMARREADER


_AUTONOMOUSVALUEREADER = _descriptor.ServiceDescriptor(
  name='AutonomousValueReader',
  full_name='AutonomousValueReader',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=630,
  serialized_end=705,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAutonomousValues',
    full_name='AutonomousValueReader.GetAutonomousValues',
    index=0,
    containing_service=None,
    input_type=_READINGS,
    output_type=_CONTROLVALUES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTONOMOUSVALUEREADER)

DESCRIPTOR.services_by_name['AutonomousValueReader'] = _AUTONOMOUSVALUEREADER


_PWMREADER = _descriptor.ServiceDescriptor(
  name='PWMReader',
  full_name='PWMReader',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=707,
  serialized_end=764,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPWMInputs',
    full_name='PWMReader.GetPWMInputs',
    index=0,
    containing_service=None,
    input_type=ArduinoMessages__pb2._CONTROLANGLES,
    output_type=ArduinoMessages__pb2._PWMVALUES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PWMREADER)

DESCRIPTOR.services_by_name['PWMReader'] = _PWMREADER


_TRIMTABGETTER = _descriptor.ServiceDescriptor(
  name='TrimTabGetter',
  full_name='TrimTabGetter',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=766,
  serialized_end=831,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTrimTabSetting',
    full_name='TrimTabGetter.GetTrimTabSetting',
    index=0,
    containing_service=None,
    input_type=TrimTabMessages__pb2._APPARENTWIND,
    output_type=TrimTabMessages__pb2._TRIMANGLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRIMTABGETTER)

DESCRIPTOR.services_by_name['TrimTabGetter'] = _TRIMTABGETTER


_WEBSERVER = _descriptor.ServiceDescriptor(
  name='Webserver',
  full_name='Webserver',
  file=DESCRIPTOR,
  index=4,
  serialized_options=None,
  serialized_start=833,
  serialized_end=902,
  methods=[
  _descriptor.MethodDescriptor(
    name='MakeServerRequest',
    full_name='Webserver.MakeServerRequest',
    index=0,
    containing_service=None,
    input_type=_SERVER_REQUEST,
    output_type=_SERVER_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEBSERVER)

DESCRIPTOR.services_by_name['Webserver'] = _WEBSERVER

# @@protoc_insertion_point(module_scope)
