# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import MessagesServices_pb2 as MessagesServices__pb2
import PWMMessages_pb2 as PWMMessages__pb2
import TrimTabMessages_pb2 as TrimTabMessages__pb2


class AirmarReaderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAirmarData = channel.unary_unary(
        '/AirmarReader/GetAirmarData',
        request_serializer=MessagesServices__pb2.req.SerializeToString,
        response_deserializer=MessagesServices__pb2.AirmarData.FromString,
        )


class AirmarReaderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAirmarData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AirmarReaderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAirmarData': grpc.unary_unary_rpc_method_handler(
          servicer.GetAirmarData,
          request_deserializer=MessagesServices__pb2.req.FromString,
          response_serializer=MessagesServices__pb2.AirmarData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AirmarReader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AutonomousValueReaderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAutonomousValues = channel.unary_unary(
        '/AutonomousValueReader/GetAutonomousValues',
        request_serializer=MessagesServices__pb2.Readings.SerializeToString,
        response_deserializer=MessagesServices__pb2.ControlValues.FromString,
        )


class AutonomousValueReaderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAutonomousValues(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AutonomousValueReaderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAutonomousValues': grpc.unary_unary_rpc_method_handler(
          servicer.GetAutonomousValues,
          request_deserializer=MessagesServices__pb2.Readings.FromString,
          response_serializer=MessagesServices__pb2.ControlValues.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AutonomousValueReader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PWMReaderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPWMInputs = channel.unary_unary(
        '/PWMReader/GetPWMInputs',
        request_serializer=MessagesServices__pb2.req.SerializeToString,
        response_deserializer=PWMMessages__pb2.PWMValues.FromString,
        )


class PWMReaderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPWMInputs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PWMReaderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPWMInputs': grpc.unary_unary_rpc_method_handler(
          servicer.GetPWMInputs,
          request_deserializer=MessagesServices__pb2.req.FromString,
          response_serializer=PWMMessages__pb2.PWMValues.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PWMReader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class RudderGetterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRudderSetting = channel.unary_unary(
        '/RudderGetter/GetRudderSetting',
        request_serializer=MessagesServices__pb2.req.SerializeToString,
        response_deserializer=TrimTabMessages__pb2.ControlAngle.FromString,
        )


class RudderGetterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRudderSetting(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RudderGetterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRudderSetting': grpc.unary_unary_rpc_method_handler(
          servicer.GetRudderSetting,
          request_deserializer=MessagesServices__pb2.req.FromString,
          response_serializer=TrimTabMessages__pb2.ControlAngle.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RudderGetter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class TrimTabGetterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTrimTabSetting = channel.unary_unary(
        '/TrimTabGetter/GetTrimTabSetting',
        request_serializer=TrimTabMessages__pb2.ApparentWind.SerializeToString,
        response_deserializer=TrimTabMessages__pb2.ControlAngle.FromString,
        )


class TrimTabGetterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTrimTabSetting(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrimTabGetterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTrimTabSetting': grpc.unary_unary_rpc_method_handler(
          servicer.GetTrimTabSetting,
          request_deserializer=TrimTabMessages__pb2.ApparentWind.FromString,
          response_serializer=TrimTabMessages__pb2.ControlAngle.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TrimTabGetter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
