# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrimTabMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TrimTabMessages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15TrimTabMessages.proto\"%\n\x0c\x43ontrolAngle\x12\x15\n\rcontrol_angle\x18\x01 \x01(\x02\"%\n\x0c\x41pparentWind\x12\x15\n\rapparent_wind\x18\x01 \x01(\x02\x62\x06proto3')
)




_CONTROLANGLE = _descriptor.Descriptor(
  name='ControlAngle',
  full_name='ControlAngle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_angle', full_name='ControlAngle.control_angle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=62,
)


_APPARENTWIND = _descriptor.Descriptor(
  name='ApparentWind',
  full_name='ApparentWind',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apparent_wind', full_name='ApparentWind.apparent_wind', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['ControlAngle'] = _CONTROLANGLE
DESCRIPTOR.message_types_by_name['ApparentWind'] = _APPARENTWIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlAngle = _reflection.GeneratedProtocolMessageType('ControlAngle', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLANGLE,
  '__module__' : 'TrimTabMessages_pb2'
  # @@protoc_insertion_point(class_scope:ControlAngle)
  })
_sym_db.RegisterMessage(ControlAngle)

ApparentWind = _reflection.GeneratedProtocolMessageType('ApparentWind', (_message.Message,), {
  'DESCRIPTOR' : _APPARENTWIND,
  '__module__' : 'TrimTabMessages_pb2'
  # @@protoc_insertion_point(class_scope:ApparentWind)
  })
_sym_db.RegisterMessage(ApparentWind)


# @@protoc_insertion_point(module_scope)
