/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Feb 26 22:30:07 2020. */

#include "ArduinoMessages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PWMValues_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, PWMValues, ch1, ch1, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, PWMValues, ch2, ch1, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, PWMValues, ch3, ch2, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, PWMValues, ch4, ch3, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, PWMValues, ch5, ch4, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, PWMValues, ch6, ch5, 0),
    PB_LAST_FIELD
};

const pb_field_t ControlAngles_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ControlAngles, rudder_angle, rudder_angle, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ControlAngles, ballast_angle, rudder_angle, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
