/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu Apr 16 07:38:08 2020. */

#ifndef PB_ARDUINOMESSAGES_PB_H_INCLUDED
#define PB_ARDUINOMESSAGES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ControlAngles {
    uint32_t rudder_angle;
    uint32_t ballast_angle;
/* @@protoc_insertion_point(struct:ControlAngles) */
} ControlAngles;

typedef struct _PWMValues {
    uint32_t ch1;
    uint32_t ch2;
    uint32_t ch3;
    uint32_t ch4;
    uint32_t ch5;
    uint32_t ch6;
/* @@protoc_insertion_point(struct:PWMValues) */
} PWMValues;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PWMValues_init_default                   {0, 0, 0, 0, 0, 0}
#define ControlAngles_init_default               {0, 0}
#define PWMValues_init_zero                      {0, 0, 0, 0, 0, 0}
#define ControlAngles_init_zero                  {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ControlAngles_rudder_angle_tag           1
#define ControlAngles_ballast_angle_tag          2
#define PWMValues_ch1_tag                        1
#define PWMValues_ch2_tag                        2
#define PWMValues_ch3_tag                        3
#define PWMValues_ch4_tag                        4
#define PWMValues_ch5_tag                        5
#define PWMValues_ch6_tag                        6

/* Struct field encoding specification for nanopb */
extern const pb_field_t PWMValues_fields[7];
extern const pb_field_t ControlAngles_fields[3];

/* Maximum encoded size of messages (where known) */
#define PWMValues_size                           36
#define ControlAngles_size                       12

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ARDUINOMESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
