/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Mon Feb 03 23:16:49 2020. */

#ifndef PB_PWMMESSAGES_PB_H_INCLUDED
#define PB_PWMMESSAGES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _PWMValues {
    float ch1;
    float ch2;
    float ch3;
    float ch4;
    float ch5;
    float ch6;
/* @@protoc_insertion_point(struct:PWMValues) */
} PWMValues;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PWMValues_init_default                   {0, 0, 0, 0, 0, 0}
#define PWMValues_init_zero                      {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PWMValues_ch1_tag                        1
#define PWMValues_ch2_tag                        2
#define PWMValues_ch3_tag                        3
#define PWMValues_ch4_tag                        4
#define PWMValues_ch5_tag                        5
#define PWMValues_ch6_tag                        6

/* Struct field encoding specification for nanopb */
extern const pb_field_t PWMValues_fields[7];

/* Maximum encoded size of messages (where known) */
#define PWMValues_size                           30

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PWMMESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
