/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Feb 19 23:54:49 2020. */

#include "TrimTabMessages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TrimAngle_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, TrimAngle, control_angle, control_angle, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, TrimAngle, state, control_angle, 0),
    PB_LAST_FIELD
};

const pb_field_t ApparentWind_fields[2] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, ApparentWind, apparent_wind, apparent_wind, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
