/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu Apr 16 07:38:07 2020. */

#include "TrimTabMessages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TrimState_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, TrimState, control_angle, control_angle, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, TrimState, state, control_angle, 0),
    PB_LAST_FIELD
};

const pb_field_t ApparentWind_Trim_fields[2] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, ApparentWind_Trim, apparent_wind, apparent_wind, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
