/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Feb 03 23:16:48 2020. */

#include "TrimTabMessages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ControlAngle_fields[2] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, ControlAngle, control_angle, control_angle, 0),
    PB_LAST_FIELD
};

const pb_field_t ApparentWind_fields[2] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, ApparentWind, apparent_wind, apparent_wind, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
