/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu Apr 16 07:38:07 2020. */

#ifndef PB_TRIMTABMESSAGES_PB_H_INCLUDED
#define PB_TRIMTABMESSAGES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _TrimState_TRIM_STATE {
    TrimState_TRIM_STATE_MAX_LIFT_PORT = 0,
    TrimState_TRIM_STATE_MAX_LIFT_STBD = 1,
    TrimState_TRIM_STATE_MAX_DRAG_PORT = 2,
    TrimState_TRIM_STATE_MAX_DRAG_STBD = 3,
    TrimState_TRIM_STATE_MIN_LIFT = 4,
    TrimState_TRIM_STATE_MANUAL = 5
} TrimState_TRIM_STATE;
#define _TrimState_TRIM_STATE_MIN TrimState_TRIM_STATE_MAX_LIFT_PORT
#define _TrimState_TRIM_STATE_MAX TrimState_TRIM_STATE_MANUAL
#define _TrimState_TRIM_STATE_ARRAYSIZE ((TrimState_TRIM_STATE)(TrimState_TRIM_STATE_MANUAL+1))

/* Struct definitions */
typedef struct _ApparentWind_Trim {
    float apparent_wind;
/* @@protoc_insertion_point(struct:ApparentWind_Trim) */
} ApparentWind_Trim;

typedef struct _TrimState {
    uint32_t control_angle;
    TrimState_TRIM_STATE state;
/* @@protoc_insertion_point(struct:TrimState) */
} TrimState;

/* Default values for struct fields */

/* Initializer values for message structs */
#define TrimState_init_default                   {0, _TrimState_TRIM_STATE_MIN}
#define ApparentWind_Trim_init_default           {0}
#define TrimState_init_zero                      {0, _TrimState_TRIM_STATE_MIN}
#define ApparentWind_Trim_init_zero              {0}

/* Field tags (for use in manual encoding/decoding) */
#define ApparentWind_Trim_apparent_wind_tag      1
#define TrimState_control_angle_tag              1
#define TrimState_state_tag                      2

/* Struct field encoding specification for nanopb */
extern const pb_field_t TrimState_fields[3];
extern const pb_field_t ApparentWind_Trim_fields[2];

/* Maximum encoded size of messages (where known) */
#define TrimState_size                           8
#define ApparentWind_Trim_size                   5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TRIMTABMESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
