# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArduinoMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ArduinoMessages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x41rduinoMessages.proto\"Y\n\tPWMValues\x12\x0b\n\x03\x63h1\x18\x01 \x01(\r\x12\x0b\n\x03\x63h2\x18\x02 \x01(\r\x12\x0b\n\x03\x63h3\x18\x03 \x01(\r\x12\x0b\n\x03\x63h4\x18\x04 \x01(\r\x12\x0b\n\x03\x63h5\x18\x05 \x01(\r\x12\x0b\n\x03\x63h6\x18\x06 \x01(\r\"<\n\rControlAngles\x12\x14\n\x0crudder_angle\x18\x01 \x01(\r\x12\x15\n\rballast_angle\x18\x02 \x01(\rb\x06proto3')
)




_PWMVALUES = _descriptor.Descriptor(
  name='PWMValues',
  full_name='PWMValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ch1', full_name='PWMValues.ch1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ch2', full_name='PWMValues.ch2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ch3', full_name='PWMValues.ch3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ch4', full_name='PWMValues.ch4', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ch5', full_name='PWMValues.ch5', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ch6', full_name='PWMValues.ch6', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=114,
)


_CONTROLANGLES = _descriptor.Descriptor(
  name='ControlAngles',
  full_name='ControlAngles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rudder_angle', full_name='ControlAngles.rudder_angle', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ballast_angle', full_name='ControlAngles.ballast_angle', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['PWMValues'] = _PWMVALUES
DESCRIPTOR.message_types_by_name['ControlAngles'] = _CONTROLANGLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PWMValues = _reflection.GeneratedProtocolMessageType('PWMValues', (_message.Message,), {
  'DESCRIPTOR' : _PWMVALUES,
  '__module__' : 'ArduinoMessages_pb2'
  # @@protoc_insertion_point(class_scope:PWMValues)
  })
_sym_db.RegisterMessage(PWMValues)

ControlAngles = _reflection.GeneratedProtocolMessageType('ControlAngles', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLANGLES,
  '__module__' : 'ArduinoMessages_pb2'
  # @@protoc_insertion_point(class_scope:ControlAngles)
  })
_sym_db.RegisterMessage(ControlAngles)


# @@protoc_insertion_point(module_scope)
