/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Oct 08 20:41:38 2019. */

#include "comms.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t vessel_state_fields[10] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, vessel_state, device_id, device_id, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, vessel_state, state, device_id, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, vessel_state, curHeelAngle, state, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, vessel_state, maxHeelAngle, curHeelAngle, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, vessel_state, controlAngle, maxHeelAngle, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, vessel_state, windAngle, controlAngle, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, vessel_state, vIn, windAngle, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, vessel_state, hallPortTrip, vIn, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, vessel_state, hallStbdTrip, hallPortTrip, 0),
    PB_LAST_FIELD
};




/* @@protoc_insertion_point(eof) */
