# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comms.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x63omms.proto\"\xd7\x01\n\x0cvessel_state\x12\x1d\n\tdevice_id\x18\x01 \x01(\x0e\x32\n.DEVICE_ID\x12\x1a\n\x05state\x18\x02 \x01(\x0e\x32\x0b.TRIM_STATE\x12\x14\n\x0c\x63urHeelAngle\x18\x03 \x01(\r\x12\x14\n\x0cmaxHeelAngle\x18\x04 \x01(\r\x12\x14\n\x0c\x63ontrolAngle\x18\x05 \x01(\r\x12\x11\n\twindAngle\x18\x06 \x01(\r\x12\x0b\n\x03vIn\x18\x07 \x01(\r\x12\x14\n\x0challPortTrip\x18\x08 \x01(\x08\x12\x14\n\x0challStbdTrip\x18\t \x01(\x08\"\x1a\n\nserver_req\x12\x0c\n\x04succ\x18\x01 \x01(\x08*l\n\nTRIM_STATE\x12\x0c\n\x08MIN_LIFT\x10\x00\x12\r\n\tSTBD_TACK\x10\x01\x12\r\n\tPORT_TACK\x10\x02\x12\x11\n\rMAX_DRAG_STBD\x10\x03\x12\x11\n\rMAX_DRAG_PORT\x10\x04\x12\x0c\n\x08MAN_CTRL\x10\x05*;\n\tDEVICE_ID\x12\x0e\n\nRIGID_SAIL\x10\x00\x12\x08\n\x04HERO\x10\x01\x12\x0b\n\x07\x41RDUINO\x10\x02\x12\x07\n\x03\x42\x42\x42\x10\x03\x32\x38\n\tWebserver\x12+\n\x0bput_message\x12\x0b.server_req\x1a\r.vessel_state\"\x00\x62\x06proto3')
)

_TRIM_STATE = _descriptor.EnumDescriptor(
  name='TRIM_STATE',
  full_name='TRIM_STATE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MIN_LIFT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STBD_TACK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PORT_TACK', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_DRAG_STBD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_DRAG_PORT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAN_CTRL', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=261,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_TRIM_STATE)

TRIM_STATE = enum_type_wrapper.EnumTypeWrapper(_TRIM_STATE)
_DEVICE_ID = _descriptor.EnumDescriptor(
  name='DEVICE_ID',
  full_name='DEVICE_ID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RIGID_SAIL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HERO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARDUINO', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BBB', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=371,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_DEVICE_ID)

DEVICE_ID = enum_type_wrapper.EnumTypeWrapper(_DEVICE_ID)
MIN_LIFT = 0
STBD_TACK = 1
PORT_TACK = 2
MAX_DRAG_STBD = 3
MAX_DRAG_PORT = 4
MAN_CTRL = 5
RIGID_SAIL = 0
HERO = 1
ARDUINO = 2
BBB = 3



_VESSEL_STATE = _descriptor.Descriptor(
  name='vessel_state',
  full_name='vessel_state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='vessel_state.device_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='vessel_state.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curHeelAngle', full_name='vessel_state.curHeelAngle', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxHeelAngle', full_name='vessel_state.maxHeelAngle', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controlAngle', full_name='vessel_state.controlAngle', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='windAngle', full_name='vessel_state.windAngle', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vIn', full_name='vessel_state.vIn', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hallPortTrip', full_name='vessel_state.hallPortTrip', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hallStbdTrip', full_name='vessel_state.hallStbdTrip', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=231,
)


_SERVER_REQ = _descriptor.Descriptor(
  name='server_req',
  full_name='server_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='succ', full_name='server_req.succ', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=259,
)

_VESSEL_STATE.fields_by_name['device_id'].enum_type = _DEVICE_ID
_VESSEL_STATE.fields_by_name['state'].enum_type = _TRIM_STATE
DESCRIPTOR.message_types_by_name['vessel_state'] = _VESSEL_STATE
DESCRIPTOR.message_types_by_name['server_req'] = _SERVER_REQ
DESCRIPTOR.enum_types_by_name['TRIM_STATE'] = _TRIM_STATE
DESCRIPTOR.enum_types_by_name['DEVICE_ID'] = _DEVICE_ID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

vessel_state = _reflection.GeneratedProtocolMessageType('vessel_state', (_message.Message,), {
  'DESCRIPTOR' : _VESSEL_STATE,
  '__module__' : 'comms_pb2'
  # @@protoc_insertion_point(class_scope:vessel_state)
  })
_sym_db.RegisterMessage(vessel_state)

server_req = _reflection.GeneratedProtocolMessageType('server_req', (_message.Message,), {
  'DESCRIPTOR' : _SERVER_REQ,
  '__module__' : 'comms_pb2'
  # @@protoc_insertion_point(class_scope:server_req)
  })
_sym_db.RegisterMessage(server_req)



_WEBSERVER = _descriptor.ServiceDescriptor(
  name='Webserver',
  full_name='Webserver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=432,
  serialized_end=488,
  methods=[
  _descriptor.MethodDescriptor(
    name='put_message',
    full_name='Webserver.put_message',
    index=0,
    containing_service=None,
    input_type=_SERVER_REQ,
    output_type=_VESSEL_STATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEBSERVER)

DESCRIPTOR.services_by_name['Webserver'] = _WEBSERVER

# @@protoc_insertion_point(module_scope)
